### ISSUE TITLE
Airsonos Yarn Installation

### ISSUE THREAD

**Issue by Ectalite** [tomodwyer/airsonos#11]
Hey,
A big thanks for forking this very useful Tool, I had just a little problem to install it with the command yarn.
It said me : 
error /home/pi/airsonos/node_modules/speaker: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/pi/airsonos/node_modules/speaker
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.9.4 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/airsonos/node_modules/speaker/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.node-gyp/8.9.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.node-gyp/8.9.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.node-gyp/8.9.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/airsonos/node_modules/speaker',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/airsonos/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: Aucun fichier ou dossier de ce type
 #include <alsa/asoundlib.h>
                            ^
compilation terminated.
deps/mpg123/output.target.mk:114: recipe for target 'Release/obj.target/output/deps/mpg123/src/output/alsa.o' failed
make: *** [Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1
make: Leaving directory '/home/pi/airsonos/node_modules/speaker/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.67-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/airsonos/node_modules/speaker
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0

I don't know what I maked false, can you help me ? 
Ectalite

**Comment by tomodwyer** [comment]
What operating system are you using?

**Comment by Ectalite** [comment]
Debian on raspberry, so Raspbian

**Comment by tomodwyer** [comment]
Could you try running `sudo apt-get install libasound2-dev` from the command line, then `yarn` install again?

**Comment by Ectalite** [comment]
Ok, it was a that, the package for dns managing wasn‘t installed too. Now the installation works, but when installed airsonos can‘t discover my sonos products(i think it‘s a problem with the new api from sonos).

**Comment by tomodwyer** [comment]
Yeah, I think this is a problem with the [node-sonos](https://github.com/bencevans/node-sonos/issues/344) package - I'll look for an update.

**Comment by tomodwyer** [comment]
Closing to track in #12
