### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by Pe8er** [tomodwyer/airsonos#3]
After a week or so of flawless Airsonos sailing, it stopped working. Here's what the console says:

```
Sep 26 19:14:40 retropie airsonos[2326]: Kitchen (@ 192.168.1.6:1400, RINCON_949F3E14C63601400:2455140802)
Sep 26 19:14:40 retropie airsonos[2326]: Search complete. Set up 1 device tunnel.
Sep 26 20:22:13 retropie airsonos[2326]: strange error flushing buffer ...
Sep 27 19:09:18 retropie airsonos[2326]: (node:2326) MaxListenersExceededWarning: Possible EventEmitter memory...limit
Sep 27 23:23:14 retropie airsonos[2326]: (node:2326) MaxListenersExceededWarning: Possible EventEmitter memory...limit
Sep 27 23:23:14 retropie airsonos[2326]: strange error flushing buffer ...
```

It works again after restarting.

**Comment by tomodwyer** [comment]
Could you put together some steps to replicate the issue?

**Comment by Pe8er** [comment]
Hey! Sorry for the late reply. I've been trying to replicate the issue and I haven't been able to. I thought it was due to intense use, but it seems to be working well so far. I'll let you know if I manage to break it again.

**Comment by tomodwyer** [comment]
No worries - I'll close the issue for now. Comment again if it happens and I'll investigate.
