### ISSUE TITLE
Airplay cipher broken?

### ISSUE THREAD

**Issue by DannyvanHolten** [tomodwyer/airsonos#6]
Whenever I try to airplay via AirParrot or Netflix (or as my guess is anything with video) on my phone I get the following error

```
strange error flushing buffer ...
strange error flushing buffer ...
strange error flushing buffer ...
strange error flushing buffer ...
strange error flushing buffer ...
```

Any idea what it means?

**Comment by tomodwyer** [comment]
@DannyvanHolten Could you provide me with your OS, Node and npm versions?

Also I wouldn't recommend using this library if you're looking to stream sound from a TV show or movie as there is a significant delay between the pictures and sound.

**Comment by DannyvanHolten** [comment]
I reckoned. Got it fixed with something else, and is unwatchable. So nvm the issue.
